---
title: "Shark data"
author: "Molly Wilson"
date: "2026-10-01"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(here)
library(purrr)
library(lubridate)
library(janitor)
library(sf)
library(ggplot2)
# library(ggspatial)
# library(patchwork)
```

# Setup
```{r}
# set fig dir
fig_dir <- here("tagging", "figs")
```

# Import + format data

## Capture data
```{r}
# Antigua
capture_anu <- read_excel(here("tagging", "data_raw", "AnuBlue shark tagging data.xlsx"), sheet = "Capture data") %>% 
  clean_names() %>%
  filter(!is.na(date)) %>%
  mutate(time = format(time, "%H:%M"),
         across(
           c(latitude, longitude, tl, fl, pcl),
           ~ suppressWarnings(as.numeric(.)))) %>%
  select(date, time, location = island, site = location, lat = latitude, lon = longitude, sex, species, length_tl = tl, length_fl = fl, length_pcl = pcl, id_floy = floy, id_pit = pit_id, id_ptt = sat_ptt) %>%
  mutate()

# Saba/SXM
capture_saba <- read_excel(here("tagging", "data_raw", "YAG shark tagging data.xlsx"), sheet = "Capture data") %>% 
  clean_names() %>%
  # fixing lat/lon formatting mess
  mutate(latitude = ifelse(
    grepl("^\\d+\\.\\d+\\.\\d+$", latitude),
    sapply(strsplit(latitude, "\\."), \(x) as.numeric(x[1]) + as.numeric(x[2]) / 60 + as.numeric(x[3]) / 60000),
    suppressWarnings(as.numeric(latitude))),
    longitude = ifelse(
      grepl("^\\d+\\.\\d+\\.\\d+$", longitude),
      sapply(strsplit(longitude, "\\."), \(x) -(as.numeric(x[1]) + as.numeric(x[2]) / 60 + as.numeric(x[3]) / 60000)),
      -abs(suppressWarnings(as.numeric(longitude)))
    )) %>%
  # fixing swapped lat/lons
  mutate(temp = latitude,
         latitude = ifelse(latitude > 19, abs(longitude), latitude),
         longitude = ifelse(temp > 19, -abs(temp), longitude)) %>%
  select(-temp) %>%
  # collapsing date and formatting time and numerics
  mutate(year = as.integer(as.numeric(year)),
         day = as.integer(as.numeric(day)),
         date = lubridate::dmy(paste(day, month, year)),
         time = format(hms::as_hms(as.numeric(time)), "%H:%M"),
         across(
           c(tl_cm, fl_cm, pcl_cm),
           ~ suppressWarnings(as.numeric(.)))) %>%
  select(date, time, location, site, lat = latitude, lon = longitude, sex, species = species_sn, length_tl = tl_cm, length_fl = fl_cm, length_pcl = pcl_cm, id_floy = floy, id_pit = pit, id_ptt = satellite_pitt)

# Merge
capture <- bind_rows(capture_anu, capture_saba) %>%
  mutate(across(everything(),
      ~ na_if(as.character(.), "NA"))) %>%
  filter(!is.na(species))
```

## Effort data

```{r}
## in raw data format times as number/time -> number/plain text

# Antigua
effort_anu <- read_excel(here("tagging", "data_raw", "AnuBlue shark tagging data.xlsx"), sheet = "Effort") %>% 
  clean_names() %>%
  mutate(across(c(start_time, end_time, set_duration),
                hms::as_hms)) %>%
  tidyr::uncount(n_rigs) %>%
  select(date, location = island, set_duration)

# Saba
effort_saba <- read_excel(here("tagging", "data_raw", "YAG shark tagging data.xlsx"), sheet = "Sets") %>%
  clean_names() %>%
  filter(!time_haul_cor %in% c("?", "-")) %>%
  mutate(date = lubridate::dmy(paste(date, month, year)),
         across(
           c(time_in_cor, time_haul_cor),
           hms::as_hms
         )) %>%
  mutate(set_duration = hms::as_hms(time_haul_cor - time_in_cor)) %>%
  filter(set_duration > 0) %>%
  select(date, location, set_duration)

# Merge
effort <- bind_rows(effort_anu, effort_saba) %>%
  mutate(across(everything(),
      ~ na_if(as.character(.), "NA")))
```

## Movement data

# Demographics
```{r}
temp <- capture %>%
  select(location) %>%
  distinct()
write.csv(temp, here(fig_dir, "sites.csv"))
```


# Mapping
```{r}
library(sf)
library(dplyr)
library(ggplot2)
library(ggspatial)

sharks_sf <- capture %>%
    mutate(
    length_tl = as.numeric(length_tl)
  ) %>%
  filter(
    !is.na(lon),
    !is.na(lat),
    !is.na(length_tl),
    !is.na(species)
  ) %>%
  st_as_sf(
    coords = c("lon", "lat"),
    crs = 4326
  )

esri_ocean <- paste0(
  "https://services.arcgisonline.com/arcgis/rest/services/",
  "Ocean/World_Ocean_Base/MapServer/tile/${z}/${y}/${x}.jpeg"
)

ggplot() +
  annotation_map_tile(
    type = esri_ocean,
    progress = "none",
    zoomin = 0
  ) +
  geom_sf(
    data = sharks_sf,
    aes(
      color = sex,
      size = length_tl
    ),
    alpha = 0.6
  ) +
  scale_size_continuous(
    name = "Total length (cm)",
    range = c(.1, 6)
  ) +
  scale_color_manual(
    values = c(
      "F" = "goldenrod1",
      "M" = "magenta4")
    ) +
  labs(
    color = "Sex",
    x = NULL,
    y = NULL
  ) +
  facet_wrap(~ species, ncol = 1) +
  theme_bw(base_size = 12) +
  theme(
    panel.grid = element_blank(),
    legend.key = element_blank()
  )

ggsave(here(fig_dir, "regional_map.png"), width = 8, height = 12)
```

